name: CI

on:
  push:
  pull_request:

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: make lint
      - run: make test
